### ISSUE TITLE
iOS 怎么正确使用该框架？

### ISSUE THREAD

**Issue by SmilngCat** [Bepal/eosio#1]
在debug模式下导出的framework加入到我自己的工程里面，可以正常运行，但是release模式下导出的framework在我的工程的release模式下，提示file was built for arm64 which is not the architecture being linked (armv7)。我的配置选项为：Bulid Active Architecture Only = NO, Valid Architectures = x86_64 arm64 armv7

**Comment by panxiaoqin** [comment]
当前不支持32位设备 且不能调用 仅支持x86_64或者arm64
