### ISSUE TITLE
关于在低版本的iOS设备上无法运行的问题

### ISSUE THREAD

**Issue by SmilngCat** [Bepal/eosio#2]
在iOS 10一下的iPhone设备上编译时，会提示secp256k1_zkp包中的“SECP256K1_GNUC_EXT typedef unsigned __int128 uint128_t”代码段里面的__int128是不支持的，请问有没有办法解决？

**Comment by panxiaoqin** [comment]
int128是32位设备无法运行的主要原因 如果能解决是可以支持32位设备 只是我们没有发现好的解决方案

**Comment by SmilngCat** [comment]
那你们现在的iOS设备上是用的这套代码吗？怎么做的兼容啊？

**Comment by panxiaoqin** [comment]
我们产品之中有硬件钱包签名在冷钱包上 其热钱包是可以不支持签名的  而int128是签名部分代码 如果是我们的轻钱包的则需要支持64位设备 否则不能生成钱包
